config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: "groups#index"
  resources :users, only: [:index,:edit, :update]
  resources :groups, only: [:new, :create, :edit, :update] do
    resources :messages, only: [:index, :create]
    
    namespace :api do
      resources :messages, only: :index, defaults: { format: 'json'}
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ApplicationRecord
  has_many :users, through: :user_groups
  has_many :messages
  has_many :user_groups
  validates :group_name, presence: true, uniqueness: true

  def show_last_message
    if (last_message = messages.last).present?
      last_message.text? ? last_message.text : '画像が投稿されています'
    else
      'まだメッセージはありません。'
    end
  end

end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :user
  belongs_to :group

  validates :text, presence: true, unless: :image?

  mount_uploader :image, ImageUploader
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :messages
  has_many :user_groups
  has_many :groups, through: :user_groups
end

app/models/user_group.rb
class UserGroup < ApplicationRecord
  belongs_to :user
  belongs_to :group
end

app/controllers/api/messages_controller.rb
class Api::MessagesController < ApplicationController
  def index
    @group = Group.find(params[:group_id])
    @messages = @group.messages.includes(:user).where('id > ?',params[:id])
    respond_to do |format|
      format.html
      format.json
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
  before_action :configure_permitted_parameters, if: :devise_controller?

  protected
  
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
  end


end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  
  before_action :set_group, only: [:edit, :update]

  def index
    @messages = Message.all
    
  end
  
  def new
    @group = Group.new
    @group.users << current_user
    @member = @group.users
  end

  def create
    @group = Group.new(group_params)
    if @group.save
      redirect_to :root, notice: 'グループを作成しました。'
    else
      render 'new'
    end
  end

  def edit
    @member = @group.users
  end

  def update
    if @group.update(group_params)
      redirect_to group_messages_path(@group), notice: 'グループを編集しました'
    else
      render :edit
    end
  end

  private
  def group_params
    params.require(:group).permit(:group_name, { :user_ids => []})
  end

  def set_group
    @group = Group.find(params[:id])
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
  before_action :set_group

  def index
    @message = Message.new
    @messages = @group.messages.includes(:user)
  end

  def create
    @message = @group.messages.new(message_params)
    if @message.save
      respond_to do |format|
        format.html { redirect_to group_messages_path(@group) }
        format.json
      end
    else
      @messages = @group.messages.includes(:user)
      respond_to do |format|
        format.html { redirect ：index }
        format.json
      end
    end
  end

  private
   def message_params
    params.require(:message).permit(:text, :image).merge(user_id: current_user.id)
   end

  def set_group
    @group = Group.find(params[:group_id])
  end
end


# Started POST "/groups/1/messages" for ::1 at 2019-09-28 13:38:01 +0900
# Processing by MessagesController#create as HTML
#   Parameters: {"utf8"=>"✓", "authenticity_token"=>"UOcpI77wilPWNBTvaPuuZWD6clybCkXtHBb2LNAiw8oWkQxHiWgrocqK2Vtc/TMppSyfAgEK7Ywq8WhDN/bDtA==", "message"=>{"text"=>"ddd", "image"=>#<ActionDispatch::Http::UploadedFile:0x00007f85baf91c48 @tempfile=#<Tempfile:/var/folders/g5/n9z2rs2x2l74rb03wngh8qw40000gn/T/RackMultipart20190928-91744-am4gar.jpg>, @original_filename="78a67_88_ca17d324867c8b09cd3a4f9164ea220a-cm.jpg", @content_type="image/jpeg", @headers="Content-Disposition: form-data; name=\"message[image]\"; filename=\"78a67_88_ca17d324867c8b09cd3a4f9164ea220a-cm.jpg\"\r\nContent-Type: image/jpeg\r\n">}, "commit"=>"Send", "group_id"=>"1"}
#   User Load (0.3ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2 ORDER BY `users`.`id` ASC LIMIT 1
#    (0.2ms)  BEGIN
#   User Load (0.2ms)  SELECT  `users`.* FROM `users` WHERE `users`.`id` = 2 LIMIT 1
#   Group Load (0.2ms)  SELECT  `groups`.* FROM `groups` WHERE `groups`.`id` = 1 LIMIT 1
#   SQL (0.2ms)  INSERT INTO `messages` (`text`, `image`, `user_id`, `group_id`, `created_at`, `updated_at`) VALUES ('ddd', '78a67_88_ca17d324867c8b09cd3a4f9164ea220a-cm.jpg', 2, 1, '2019-09-28 04:38:01', '2019-09-28 04:38:01')
#    (0.5ms)  COMMIT

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
    @users = User.where('name LIKE(?) and (id!=?)' , "#{params[:keyword]}%", "#{current_user.id}").where.not(id: params[:user_ids])
    respond_to do |format|
      format.json 
    end
  end
  
  def edit
  end

  def update
    if current_user.update(user_params)
      redirect_to root_path
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.haml
= form_for (group) do |f|
  - if group.errors.any? 
    .chat-group-form__errors
      %h2= "#{group.errors.full_messages.count}件のエラーが発生しました。"
      %ul
        - group.errors.full_messages.each do |message|
          %li= message
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :group_name, class:'chat-group-form__label'
    .chat-group-form__field--right
      = f.text_field :group_name, placeholder: "グループ名を入力してください", id: 'chat_group_name', class: 'chat-group-form__input'
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :users, "チャットメンバーを追加", class: 'chat-group-form__label', for: 'user-search-field'
    .chat-group-form__field--right
      .chat-group-form__search.clearfix
        = f.text_field :users, id: "user-search-field", class:"chat-group-form__input", value:'', placeholder: "追加したいユーザー名を入力してください"
      #user-search-result
  .chat-group-form__field.clearfix
    .chat-group-form__field--left
      = f.label :members, class: 'chat-group-form__label' do
        チャットメンバー
    .chat-group-form__field--right
      .chat-group-users.js-add-user
        - @member.each do |user|
          .chat-group-user.clearfix.js-chat-member{id: "#{user.id}"}
            = f.hidden_field :user_ids, {name: 'group[user_ids][]', id: "group_user_ids", value: "#{user.id}"}
            %p.chat-group-user__name
              = user.name
            %a.chat-group-user__btn.chat-group-user__btn--remove.js-remove-btn 削除 
  .chat-group-form__field.clearfix
    .chat-group-form__field--right
      = f.submit class: 'chat-group-form__action-btn' 

app/views/groups/edit.html.haml
.chat-group-form
  %h1 チャットグループ編集
  = render partial: 'form', locals: {group: @group, member: @member}

app/views/groups/index.html.haml
.wrapper
  = render partial: "shared/side"
  = render partial: "shared/main" unless 'index'

app/views/groups/new.html.haml
.chat-group-form
  %h1 新規チャットグループ
  = render 'form', {group: @group, member: @member}

app/views/layouts/_flash.html.haml
.flash-box
  - flash.each do |key, value|
    = content_tag :div, value, class: key

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title ChatSpace
    = csrf_meta_tags
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    = render partial: "layouts/flash"
    = yield

app/views/messages/index.html.haml
.wrapper
  .chat-side
    .side-header
      .side-header__box
        %p.side-header__box__user-name 
          = current_user.name
        %ul.side-header__box__menu
          %li.side-header__box__menu__new-group
            = link_to '#' do
              %i.fa.fa-edit
          %li.side-header__box__menu__edit-user
            = link_to edit_user_path(current_user), method: :get do
              %i.fa.fa-cog
    .groups
      = render partial: "group"

  .chat-main
    .main-header
      .main-header__left-box
        %h2.main-header__left-box__current-group{"data-group_id": "1359"} サッカー
        %ul.main-header__left-box__member-list
          Member：
          %li.main-header__left-box__member-list__member Taro
          %li.main-header__left-box__member-list__member Syogo
        = link_to '#' do
          .main-header__edit-btn Edit
    .messages
      = render partial: "message"

    .form
      %form#new_message.new_message{"accept-charset": "UTF-8", action: "/groups/1408/messages", enctype: "multipart/form-data", method: "post"}
        .form-box
          %input.form-box__text{placeholder: "type a message",type: "text"}
            %label.form-box__image{for: "message_image"}
              %i.fa.fa-image
              %input#message_image.form-box__image__file{name: "message_image", type: "file"}/
        = link_to '#' do
          .submit-btn Send

app/views/shared/_main.html.haml
.chat-main
  .main-header
    .main-header__left-box
      %h2.main-header__left-box__current-group
        = @group.group_name
      %ul.main-header__left-box__member-list
        Member：
        = render partial: 'shared/member', locals: {group: @group}
      = link_to edit_group_path(@group) do
        .main-header__edit-btn Edit
  .messages
    = render partial: 'shared/message', collection: @messages
  .form
    #new_message.new_message
    = form_for [@group,@message] do |f|
      .form-box
        = f.text_field :text, class: 'form-box__text', placeholder: "type a message"
        = f.label :image, class: 'form-box__image', for: "message_image" do
          = fa_icon 'picture-o', class: 'fa'
          = f.file_field :image, id: 'message_image', class: 'form-box__image__file'
      = f.submit "Send", class: 'submit-btn' 

app/views/shared/_member.html.haml
- group.users.each do |user|
  %li.main-header__left-box__member-list__member= user.name

app/views/shared/_message.html.haml
.message{"data-id": "#{message.id}"}
  .message__upper-info   
    %p.message__upper-info__talker#message-user_name
      = message.user.name
    %p.message__upper-info__date#message-date
      = message.created_at .strftime("%Y/%m/%d %H:%M")
  - if message.text.present?
    %p.message__text#message-text
      = message.text
  =image_tag message.image if message.image.present?



  

app/views/shared/_side.html.haml
.chat-side
  .side-header
    .side-header__box
      %p.side-header__box__user-name 
        = current_user.name
      %ul.side-header__box__menu
        %li.side-header__box__menu__new-group
          = link_to new_group_path do
            %i.fa.fa-edit
        %li.side-header__box__menu__edit-user
          = link_to edit_user_path(current_user), method: :get do
            %i.fa.fa-cog
  .groups
    - current_user.groups.each do |group|
      = link_to group_messages_path(group) do
        .group
          %p.group__group-name 
            = group.group_name
          %p.group__latest-message
            = group.show_last_message
            

app/views/users/edit.html.haml
#account-page.account-page
  .account-page__inner.clearfix
    .account-page__inner--left.account-page__header
      %h2 Edit Account
      %h5 アカウントの編集
      = link_to "ログアウト", destroy_user_session_path, method: :delete, class: 'btn'
      = link_to "トップページに戻る", :back, class: 'btn'
    .account-page__inner--right.user-form
      = form_for(current_user) do |f|
        .field
          .field-label
            = f.label :name
          .field-input
            = f.text_field :name, autofocus: true
        .field
          .field-label
            = f.label :email
          .field-input
            = f.email_field :email
        .actions
          = f.submit "Update", class: 'btn'